text = "Шелудянкин Александр Константинович ИСБ-119"
alphabet = ""

for i in text:
    if i not in alphabet:
        alphabet += i

print(f'{alphabet}, length alphabet = {len(alphabet)}, length text = {len(text)}')

s = "aaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdvaaaayyxxaaabaaayyyabxxxbaxxxxxaaaabybwqeqwqscscwwvwdv"
print(len(s))

